417 reorder table column table
SETI/rms-opus pull request #1096
Opened 2020-08-22 00:36 UTC by dstopp

- Fixes #417 
- Were any Django, import pipeline, table_schema, or dictionary files modified? N
  - If YES:
    - Database used: opus3_test_200729
    - All Django tests pass: Y/NA
    - FLAKE8 run on modified code: Y/NA
- Were any JavaScript or CSS files modified? Y
  - If YES:
    - JSHINT run on all affected files: Y
    - Tested on Chrome, Firefox, Safari, Edge, and iOS: <still testing>
      (Remember to test all browser sizes)
    - Tested for race conditions (with delayed API calls if applicable): <still testing>

Description of changes:
 - added a dropdown toolbar to the table header that allows users to add either before or after the metadata element a new metadata field OR remove the selected metadata field.  

Known problems:
 - code for the reorder of the table headers is still in place but commented out

2020-08-24 18:24 UTC, rfrenchseti requested changes
- I haven't found a way to reproduce it with 100% reliability, but if you add and delete columns a lot you eventually get to a state where the "add/delete" toolbar ends up on top of the header, instead of below. Once it's there, it never gets better. When this happens, it's also slightly offset from the header position - a few pixels to the right.

2020-08-24 18:24 UTC, rfrenchseti commented on opus/application/static_media/js/utils.js
> +// more convienent this way...
Spell convenient

2020-08-24 18:24 UTC, rfrenchseti commented on opus/application/apps/ui/templates/ui/base.html
> +        <div id="op-obs-menu" class="dropdown-menu dropdown-menu-sm"data-toggle="dropdown" aria-labelledby="op-obs-menu" aria-haspopup="true" aria-expanded="false">
Missing space before data-toggle

2020-08-24 18:24 UTC, rfrenchseti commented on opus/application/apps/ui/templates/ui/base.html
> +        <!-- drodown menu for adding metadata fields -->
Spell dropdown

2020-08-24 18:24 UTC, rfrenchseti commented on opus/application/static_media/css/opus.css
> +.#galleryView .op-metadata-detail-add {
Is there an extra "." before #galleryView?

2020-08-24 18:24 UTC, rfrenchseti commented on opus/application/static_media/css/opus.css
> +absolute, and this will result its child element ui-resizable (position: relative)
Bad grammar

2020-08-24 18:24 UTC, rfrenchseti commented on opus/application/static_media/js/browse.js
> +            switch(action) {
Space after switch

2020-08-24 18:24 UTC, rfrenchseti commented on opus/application/static_media/js/browse.js
> +            let cols;
Why is cols set outside of the loop?

2020-08-24 18:24 UTC, rfrenchseti commented on opus/application/static_media/js/browse.js
> +                let columnOrder = $(this).sortable( "toArray" );
Extra spaces

2020-08-24 18:24 UTC, rfrenchseti commented on opus/application/static_media/js/browse.js
> +
Extra blank line

2020-08-24 18:24 UTC, rfrenchseti commented on opus/application/static_media/js/browse.js
> +        // passing in false indicates to not close the gallery view on loadData
Passing in false to what?

2020-08-24 18:24 UTC, rfrenchseti commented on opus/application/static_media/js/browse.js
> +
Extra blank line

2020-08-24 18:24 UTC, rfrenchseti commented on opus/application/static_media/js/browse.js
> +        let targetPosition = $(e.currentTarget).offset();
Something in here seems to have changed. With a little work I can get the *slideshow* add-metadata dropdown to dropup when it shouldn't, and run a little off the top of the browser. If I have exactly the same screen on the production OPUS, it doesn't do it.

2020-08-24 18:24 UTC, rfrenchseti commented on opus/application/static_media/js/browse.js
> +        // if there is only one metadata field left, disable the trash in both the gallery view and table tools dropdown
Gallery view? Do you mean slideshow?

2020-08-27 18:46 UTC, dstopp commented
All comments have been addressed except the one that causes the toolbar to get slightly offset.

2020-08-28 00:19 UTC, rfrenchseti approved these changes

2020-08-28 00:20 UTC, merged