1059 resize dock slideshow dialog
SETI/rms-opus pull request #1103
Opened 2020-10-13 03:30 UTC by dstopp

- Fixes #1059 
- Were any Django, import pipeline, table_schema, or dictionary files modified? Y/N
  - If YES:
    - Database used: opus3_test_200903
    - All Django tests pass: Y
    - FLAKE8 run on modified code: NA
- Were any JavaScript or CSS files modified? Y
  - If YES:
    - JSHINT run on all affected files: Y
    - Tested on Chrome, Firefox, Safari, Edge, and iOS: Y
      (Remember to test all browser sizes)
    - Tested for race conditions (with delayed API calls if applicable): NA

Description of changes:
-Allow the galleryView/slide show modal to be resized;
-Provide min/max icons for instant resize;
-move the image to the top of the column when the modal narrows;
-change the font size and icon fonts to smaller when the modal becomes small;
-minor changes to update class names for code consistancy;
-Docking code is present but currently commented out

Known problems:

2020-10-16 06:03 UTC, juzen2003 requested changes
- Observed issues:
    - When the modal is first open, its size is a bit larger than the default size.
        - Steps to reproduce:
            1. Start at browse tab freshly (like after a refresh), and open up the gallery view modal (default size). 
            2. Click the .op-slide-maximize button, the modal size will shrink a little bit (very little). 
    - The default size of the modal will not change when browser screen is resized, not sure if this is the expected behavior.
       - Steps to reproduce:
            1. Start at browse tab freshly and open up the gallery view modal.
            2. Click the .op-slide-maximize button and close the modal.
            3. Reduce the height of browser window to be smaller than the modal height 
            4. Open the modal again, the modal will be big and cover the whole window. If we don't click the .op-slide-maximize button at step b, the modal will open with the correct size.
    - After a certain amount of modal resizing and moving, the newly open modal will always stay at the right and outside of the browser window.
        - Steps to reproduce:
            1. Start at browse tab freshly.
            2. Open a modal, resize & move, and then click the .op-slide-maximize button and close the modal.
            3. Open a modal again, the modal will stay outside of the browser window (at the right). Repeat step b if the modal open up within the browser window. 
    - When modal height is short and the image is still at the left, the metadata detail text will overlap with the ".op-cart-toggle" icon. Example size: 505 x 292

2020-10-16 06:03 UTC, juzen2003 commented on opus/application/static_media/css/opus.css
> +    /*align-self: center; */
Remove unwanted style.

2020-10-16 06:03 UTC, juzen2003 commented on opus/application/static_media/css/opus.css
> +    /*max-height: 80vh !important;*/
Remove unwanted style.

2020-10-16 06:03 UTC, juzen2003 commented on opus/application/static_media/css/opus.css
> +/* #################################### */
Sorry I forgot to remove this when creating pull to your repo.

2020-10-16 06:03 UTC, juzen2003 commented on opus/application/static_media/js/browse.js
> +        $('.op-slide-minimize').on("click", function(e) {
Use double quotes to meet our js code styles.

2020-10-16 06:03 UTC, juzen2003 commented on opus/application/static_media/js/browse.js
> +        $('.op-slide-maximize').on("click", function(e) {
Use double quotes.

2020-10-16 06:03 UTC, juzen2003 commented on opus/application/static_media/js/browse.js
> +        $('.op-slide-dock').on("click", function(e) {
Use double quotes.

2020-10-16 06:03 UTC, juzen2003 commented on opus/application/static_media/js/browse.js
> +        $('.op-gallery-view-body').on("click", "a.op-cart-toggle", function(e) {
Use double quotes.

2020-10-16 06:03 UTC, juzen2003 commented on opus/application/static_media/js/browse.js
> +        $('.op-gallery-view-body').on("click", "a.op-prev,a.op-next", function(e) {
Use double quotes.

2020-10-16 06:03 UTC, juzen2003 commented on opus/application/static_media/js/browse.js
> +            $(`#op-add-metadata-fields .op-select-list`).addClass("op-resize-small");
Since there is no string interpolation, we can use " instead of `, same at line 1205.

2020-10-16 06:03 UTC, juzen2003 commented on opus/application/static_media/js/browse.js
> +        $("#op-gallery-view-content .row.bottom").removeClass( function(index, css) {
An extra space is between ( and function.

2020-10-16 06:03 UTC, juzen2003 commented on opus/application/static_media/js/browse.js
> +        let browseDialogHeight = $(`.op-gallery-view-body .op-metadata-details .contents`).height();
Since there is no string interpolation, we can use " instead of `, same at line 2378, 2379, 2383, 2548, and 2589.

2020-10-16 06:03 UTC, juzen2003 commented on opus/application/static_media/js/cart.js
> +        $(`.op-gallery-view-body .op-cart-toggle`).html(`<i class="${buttonInfo[tab].icon} fa-2x float-left"></i>`);
Replace ` with " in the selector.

2021-09-27 21:25 UTC, juzen2003 requested changes
- Database used: opus3_test_210526
- All Django tests pass: Y
- JSHINT run on all affected files: Y
- FLAKE8 run on all affected files: Y
- Tested on Chrome, Firefox, Safari, and iOS: Y
  (Remember to test all browser sizes)
- Tested for race conditions (with delayed API calls if applicable): NA

- Issue:
  - When the slide show dialog is not min/max, the size of the modal will increase every time when the browser window is resize (either increase/decrease the window size).
      - steps to reproduce:
          1. Make the slide show dialog small manually, and keep the browser window relatively big.
          2. Slightly increase the height of the browser window, the modal size will increase
          3. Slightly decrease the height of the browser window, the modal size will keep increasing a little bit.
          4. Keep doing step 2 & 3, we can see that modal size keep increasing but browser window size is not changing.

2021-09-27 21:25 UTC, juzen2003 commented on opus/application/static_media/js/browse.js
> +            top = 0
missing `;`

2021-10-03 15:47 UTC, dstopp commented on opus/application/static_media/css/opus.css
> +    /*max-height: 80vh !important;*/
done

2021-10-03 15:48 UTC, dstopp commented on opus/application/static_media/css/opus.css
> +/* #################################### */
done

2021-10-03 15:50 UTC, dstopp commented on opus/application/static_media/js/browse.js
> +        $('.op-slide-minimize').on("click", function(e) {
done

2021-10-03 15:50 UTC, dstopp commented on opus/application/static_media/js/browse.js
> +        $('.op-slide-maximize').on("click", function(e) {
done

2021-10-03 15:51 UTC, dstopp commented on opus/application/static_media/js/browse.js
> +        $('.op-slide-dock').on("click", function(e) {
done

2021-10-03 15:51 UTC, dstopp commented on opus/application/static_media/js/browse.js
> +        $('.op-gallery-view-body').on("click", "a.op-cart-toggle", function(e) {
done

2021-10-03 15:51 UTC, dstopp commented on opus/application/static_media/js/browse.js
> +        $('.op-gallery-view-body').on("click", "a.op-prev,a.op-next", function(e) {
done

2021-10-03 15:52 UTC, dstopp commented on opus/application/static_media/js/browse.js
> +            $(`#op-add-metadata-fields .op-select-list`).addClass("op-resize-small");
done

2021-10-03 15:53 UTC, dstopp commented on opus/application/static_media/js/browse.js
> +        $("#op-gallery-view-content .row.bottom").removeClass( function(index, css) {
done

2021-10-03 16:04 UTC, dstopp commented on opus/application/static_media/js/cart.js
> +        $(`.op-gallery-view-body .op-cart-toggle`).html(`<i class="${buttonInfo[tab].icon} fa-2x float-left"></i>`);
done

2021-10-03 16:04 UTC, dstopp commented on opus/application/static_media/js/browse.js
> +        let browseDialogHeight = $(`.op-gallery-view-body .op-metadata-details .contents`).height();
done

2021-10-03 16:05 UTC, dstopp commented on opus/application/static_media/js/browse.js
> +            top = 0
done

2021-10-03 20:05 UTC, rfrenchseti requested changes
- When a thumbnail has the mini-binoculars showing (it was the last observation in the slideshow), you can't click anywhere near the top of the thumbnail and have the slideshow come up again. The entire top of the thumbnail is nonresponsive. Thumbnails that don't have the mini-binoculars showing work fine. Note the same thing happens when "DETAIL" is shown. If you click in the area near the DETAIL, nothing happens. I think in all cases the slideshow should appear.
- When you have a browser that is <= 9 thumbnail rows tall, when you click on a thumbnail the default position for the slideshow extends below the footer. It's one thing to allow people to drag the slideshow dialog that low, but something else to make that the default position.
- If you keep clicking on a thumbnail and closing the dialog by hitting ESC without moving the mouse, the dialog will show up in a different vertical position each time.

2021-10-12 17:56 UTC, rfrenchseti approved these changes

2021-11-01 22:39 UTC, merged