Add formats DMS/HMS and datetime
SETI/rms-opus pull request #1152
Opened 2021-04-23 18:26 UTC by rfrenchseti

- Fixes #599, #1030
- Were any Django, import pipeline, table_schema, or dictionary files modified? Y
  - If YES:
    - Database used: New
    - All Django tests pass: Y
    - FLAKE8 run on modified code: Y
- Were any JavaScript or CSS files modified? Y/N
  - If YES:
    - JSHINT run on all affected files: Y/NA
    - Tested on Chrome, Firefox, Safari, Edge, and iOS: Y/NA
      (Remember to test all browser sizes)
    - Tested for race conditions (with delayed API calls if applicable): Y/NA

Description of changes:

Known problems:

2021-04-27 02:18 UTC, rfrenchseti commented
- Date/time formats:
  - The "julian" module handles the following formats: YYYY-MM-DD[THH:MM:SS.sss], YYYY-DDD[THH:MM:SS.sss], JDxxxx, JEDxxxx, MJDxxxx, MJEDxxxx.
  - All of those formats are supported by just typing them raw into a date/time field, regardless of the currently selected units. In other words, if the current unit is "JD", you can still type "2010-01-01".
  - If you just type a number, it is interpreted according to the current unit selection.
  - Dates are limited to the years 1000-2999; anything outside of that range is considered an error
- RA/DEC/longitude/latitude formats:
  - Nd Nm Ns (degrees-minutes-seconds) or Nh Nm Ns (hours-minutes-seconds).
  - The last field (d/h, m, or s) can have fractions, but none of the earlier fields can. So "1.23d" and "1d 2.34m" are legal but "1.23d 10m" is not.
  - You can type a degrees string during "hours" units or vice versa and it will be interpreted properly.
  - You can type either a degrees or hours string during radians and it will be interpreted properly.
  - If you type a raw number, it will be interpreted according to the current units: degrees or DMS means degrees, hours or HMS means hours, radians mean radians.
- Numeric fields that support other types of units (duration, distance, resolution, etc.) can take an optional suffix to override the unit. So when "seconds" is selected, you can type "1" which means 1 second. Or you can type "1 day" or "1 hour" and it will convert for you. There are a wide range of things that will be understood.
- Spacing and capitalization shouldn't matter for any of the above as long as it doesn't introduce an ambiguity.

2021-04-27 02:20 UTC, rfrenchseti commented
One more change: I increased the number of significant digits for wave number and wave number resolution.

2021-04-27 05:37 UTC, juzen2003 commented
One issue found so far, for observation time, we can't switch unit to JED or MJED, here are steps to reproduce:
  - Start OPUS freshly, open up Observation Time widget.
  - In unit selection, change unit to JED or MJED, the spinner will stay, hints won't get updated, and there will be a server error.

2021-04-29 20:17 UTC, juzen2003 requested changes
Input width for datetime text (Test on latest version of each browser):
- Test example: put "1981-08-12T14:55:10.080" in min input.
- MAC (Big Sur): 
    - Chrome, Safari, Opera, and Edge will have text overflow
    - Firefox will not have text overflow.
- Window 10:
    - Chrome, Firefox, Edge, and Opera will not have overflow.

2021-04-29 20:17 UTC, juzen2003 commented on lib/opus_support.py
> +            ret = ret.rstrip('0').rstrip('.')
I think the following issue is caused by this, it will strip the last 0 when number is in the format like 8e+10 (got converted to 8e+1). Will have to set keep_trailing_zeros to True when the input has scientific format.
Issue:
- Open Observation duration widget.
- Change unit to days, and type 1 in any input.
- Change unit to usecs, and it will convert 1 day to 8.64e+1 instead of 8.64e+10

Or call this API for the same action:
- http://127.0.0.1:8000/opus/__api/normalizeinput.json?reqno=1&observationduration2_101=1&unit-observationduration_101=microseconds&sourceunit-observationduration_101=days&unit-observationduration_102=microseconds&sourceunit-observationduration_102=days

2021-04-30 19:01 UTC, rfrenchseti commented on lib/opus_support.py
> +            ret = ret.rstrip('0').rstrip('.')
Fixed. I also fixed the case of 1.000e+10 not turning into 1e+10. New tests have been added.

2021-04-30 20:22 UTC, juzen2003 approved these changes
- Database used: opus3_test_210331
- All Django tests pass: Y
- JSHINT run on all affected files: NA
- FLAKE8 run on all affected files: Y
- Tested on Chrome, Firefox, Safari, and iOS: Y
  (Remember to test all browser sizes)
- Tested for race conditions (with delayed API calls if applicable): NA

2021-05-03 17:39 UTC, merged