Import for vg 28xx occ
SETI/rms-opus pull request #1174
Opened 2021-06-17 19:35 UTC by juzen2003

This pull request is to track the progress of adding VG_28xx to OPUS: (need to work with this pdsfile branch: https://github.com/SETI/pds-webtools/pull/38)
- Items done:
    - Add import steps for VG_28xx (profile index files are under Shared-OPUS/pdsdata/holdings/metadata/VG_28xx)
- To do items:
    - In OPUS, update the ring geometry values in the import for VG_28xx 
    - In pdsfile, add rules for VG_28xx
    - In OPUS, add api results test for VG_28xx

2021-07-09 17:42 UTC, rfrenchseti requested changes
- I reviewed UVS first so look there for more complete comments that are applicable to the other instruments.
- I think the obs_occultation table should be renamed to obs_profile to be consistent. When doing the search-and-replace be careful not to replace things improperly. It's best to use case-matching so you don't change comments. Then do a second replace on OBS_OCCULTATION to OBS_PROFILE with case-matching.
- You need to rename "Occultation Constraints" to whatever it was we had decided on, perhaps "Occultation&Reflectance Profile Constraints". Unfortunately I can't find my notes but perhaps you wrote it down.

2021-07-09 17:42 UTC, rfrenchseti commented on opus/application/apps/results/test_results.py
> +                    'obs_mission_voyager']
We have triggered table tests for each mission and each instrument. So let's add new tests for the new Voyager instruments (PPS, UVS, RSS) below after VGISS.

2021-07-09 17:42 UTC, rfrenchseti commented on opus/import/config_data.py
> +VOLUME_ID_TO_INSTRUMENT_NAME = {
Is this needed? I think it's covered in the dict above.

2021-07-09 17:42 UTC, rfrenchseti commented on opus/import/import_util.py
> +                    volume_descs.append('VG_28xx')
I don't think this does the right thing. VOYAGER should mean VGISS and VG_28xx but it is only giving VG_28xx because of the "elif" below.

2021-07-09 17:42 UTC, rfrenchseti commented on opus/import/import_util.py
> +                    volume_descs.append('VG_28xx')
Also should add options for VGUVS, VGPPS, and VGRSS.

2021-07-09 17:42 UTC, rfrenchseti commented on opus/import/import_for_tests.sh
> +python main_opus_import.py --do-all-import VG_2801 VG_2802 VG_2803 VG_2810 $1
Maybe this should be VG_28xx instead?

2021-07-09 17:42 UTC, rfrenchseti commented on opus/import/populate_obs_mission_voyager.py
>  ################################################################################
Put a blank line or two here

2021-07-09 17:42 UTC, rfrenchseti commented on opus/import/table_schemas/obs_general.json
> +              [   7, "INT",    "Intensity Profile", "080", "Y", null]
I think this should be "reflectance". Technically an occultation is intensity, since we're seeing how bright a star is when it's seen through a ring. Also we call it "reflectance" in the occultation type table.

2021-07-09 17:42 UTC, rfrenchseti commented on opus/import/table_schemas/obs_occultation.json
> +              [   6, "VISUAL", "Visual",  "070", "Y", null],
I'm not sure what "VISUAL" means. Isn't this the same as "Visible"? For light visible to the naked eye.

2021-07-09 17:42 UTC, rfrenchseti commented on opus/import/populate_obs_instrument_VGUVS_prof.py
> +# populate_obs_instrument_VGUVS_occ.py
Filename at the top of this and all other _occ files is wrong - should be _prof

2021-07-09 17:42 UTC, rfrenchseti commented on opus/import/populate_obs_instrument_VGUVS_prof.py
> +    # return 'VG'
Remove

2021-07-09 17:42 UTC, rfrenchseti commented on opus/import/populate_obs_instrument_VGUVS_prof.py
> +def _integration_duration_helper(**kwargs):
I don't think this is used, since there is no INTEGRATION_DURATION column in the supp index.

2021-07-09 17:42 UTC, rfrenchseti commented on opus/import/populate_obs_instrument_VGUVS_prof.py
> +    return wl_band
I don't understand this function. The return value has to be either a single string, or a tuple of strings where one is what we put in the database and the other is what we display to the user next to a checkbox. But it looks like you could be returning [wl_band1, wl_band2], which is a pair of strings that have nothing to do with each other, so what you put in the database and what you display to the user are unrelated. We can't have two wavelength bands for a single observation; we have to choose one. Are there actually cases where the bands are different?

2021-07-09 17:42 UTC, rfrenchseti commented on opus/import/populate_obs_instrument_VGUVS_prof.py
> +    return src_name
Same issue as above - we can't have two different sources for a single observation. If they're different, we have to pick one. I can't imagine they are ever different, though, are they?

2021-07-09 17:42 UTC, rfrenchseti commented on opus/import/populate_obs_instrument_VGUVS_prof.py
> +# hit the ring, to the north pole of the earth (normal vector
Not north pole of the earth... the pole on whatever planet you're looking at that's on the lit side of the rings.

2021-07-09 17:42 UTC, rfrenchseti commented on opus/import/populate_obs_instrument_VGISS.py
> -# There is nothing instrument-specific for Voyager.
This file should be renamed to _obs.

2021-07-09 17:42 UTC, rfrenchseti commented on opus/import/populate_obs_instrument_VGUVS_prof.py
> +
Remove blank line to be consistent with wavelength1

2021-07-09 17:42 UTC, rfrenchseti commented on opus/import/populate_obs_instrument_VGUVS_prof.py
> +### populate_obs_occultation TABLE ###
This comment was previously wrong in all the files - can you fix it? It should say "### OBS_OCCULTATION TABLE ###"

2021-07-09 17:42 UTC, rfrenchseti commented on opus/import/populate_obs_instrument_VGUVS_prof.py
> +def _is_Voyager_at_north(**kwargs):
Move this above first use so it's easier to find. Also don't capitalize Voyager - we don't normally have capital letters in function names unless it's something special like an abbreviation.

2021-07-09 17:42 UTC, rfrenchseti commented on opus/import/populate_obs_instrument_VGUVS_prof.py
> +# side of the ring , negative if it's at the south side. If observer is at the
Extra space before comma

2021-07-09 17:42 UTC, rfrenchseti commented on opus/import/populate_obs_instrument_VGUVS_prof.py
> +        target_name = populate_target_name_from_index(**kwargs)
How about a new function called something like _is_voyager_at_north_except_uranus. Then you don't have to hard-code the target name stuff in every function here and you can remove one level of IFs as well.

2021-07-09 17:42 UTC, rfrenchseti commented on opus/import/populate_obs_instrument_VGUVS_prof.py
> +    if (src_name == "DELTA SCO"
You can just return the result of the comparison without any IF

2021-07-09 17:42 UTC, rfrenchseti commented on opus/import/populate_obs_instrument_VGUVS_prof.py
> +# THESE NEED TO BE IMPLEMENTED FOR EVERY voyager INSTRUMENT
Another bad search-and-replace that might be historical but you can fix. Make VOYAGER all caps in this comment in all relevant files.

2021-07-09 17:42 UTC, rfrenchseti commented on opus/import/populate_obs_instrument_VGRSS_prof.py
> +    # return 'VG'
Remove

2021-07-09 17:42 UTC, rfrenchseti commented on opus/import/populate_obs_instrument_VGRSS_prof.py
> +
Remove

2021-07-09 17:42 UTC, rfrenchseti commented on opus/import/populate_obs_instrument_VGRSS_prof.py
> +def _integration_duration_helper(**kwargs):
Remove

2021-07-09 17:42 UTC, rfrenchseti commented on opus/import/populate_obs_instrument_VGRSS_prof.py
> +    target_name = populate_target_name_from_index(**kwargs)
Use new function per UVS

2021-07-09 17:42 UTC, rfrenchseti commented on opus/import/populate_obs_instrument_VGPPS_prof.py
> +    # return 'VG'
Remove

2021-07-09 17:42 UTC, rfrenchseti commented on opus/import/populate_obs_instrument_VGPPS_prof.py
> +
Remove

2021-07-09 17:42 UTC, rfrenchseti commented on opus/import/populate_obs_instrument_VGPPS_prof.py
> +    if _is_Voyager_at_north(**kwargs):
New function

2021-07-09 17:42 UTC, rfrenchseti commented on opus/import/populate_obs_instrument_VGISS_prof.py
> +    # return 'VG'
Remove

2021-07-13 15:40 UTC, juzen2003 commented
Codes are updated based on feedback, will have to update tests later after pds-webtools (https://github.com/SETI/pds-webtools/pull/39/files) is finalized.

2021-08-07 00:47 UTC, juzen2003 commented
- Fixes #1121 
- Were any Django, import pipeline, table_schema, or dictionary files modified? Y
  - If YES:
    - Database used: Import a new test database
    - All Django tests pass: Y
    - FLAKE8 run on modified code: Y
- Were any JavaScript or CSS files modified? N
  - If YES:
    - JSHINT run on all affected files: NA
    - Tested on Chrome, Firefox, Safari, Edge, and iOS: NA
      (Remember to test all browser sizes)
    - Tested for race conditions (with delayed API calls if applicable): NA

Description of changes:
- Add import for VG_28xx
- Update tests results based on the latest VG_28xx rules  https://github.com/SETI/pds-webtools/pull/39
Known problems:

2021-08-24 18:37 UTC, rfrenchseti requested changes
Many opus product types do not have tooltip descriptions. At least these:

vgpps_occ_best
vgpps_occ_02
vgpps_occ_05
vgpps_occ_raw
vgpps_occ_cal
vgpps_occ_geo
vgpps_occ_img
vgpps_occ_jit
vgpps_occ_j2000
vgpps_occ_ring
vgpps_occ_test
vgrss_occ_inv0_05
vgrss_occ_inv0_5
vgrss_occ_sam0_025
vgrss_occ_sam0_05
vgrss_occ_sam0_1
vgrss_occ_sam0_2
vgrss_occ_sam0_5
vguvs_occ_full_res
vguvs_occ_sampled_2
vguvs_occ_sampled_3
vguvs_occ_sampled_4
vguvs_occ_sampled_5
vguvs_occ_02
vguvs_occ_05
vguvs_occ_10
vguvs_occ_coadd
vguvs_occ_spec
vguvs_occ_cal
vguvs_occ_geo
vguvs_occ_img

2021-08-24 18:37 UTC, rfrenchseti commented on opus/application/test_api/test_results_contents.py
> +    ####################
Add black line above ######

2021-08-24 18:37 UTC, rfrenchseti commented on opus/application/test_api/test_results_contents.py
> +    ####################
Add blank line above #######

2021-08-24 18:37 UTC, rfrenchseti commented on opus/import/import_util.py
>                  elif desc.upper() == 'VOYAGER' or desc.upper() == 'VGISS':
The comparisons with 'VOYAGER' here and below don't do anything because it was already caught above.

2021-08-24 18:37 UTC, rfrenchseti commented on opus/import/populate_obs_mission_voyager.py
> +    # For occulation, we will fetch data from profile index
This comment doesn't say anything useful. How about "For a profile, we derive the mission phase from the target name"?

2021-08-24 18:37 UTC, rfrenchseti commented on opus/import/table_schemas/obs_general.json
> +              [   9,       "VGRSS",            "Voyager RSS", "100", "Y", null],
VGRSS should be after VGPPS to be in alphabetical order

2021-08-24 18:37 UTC, rfrenchseti commented on opus/import/config_data.py
> +                         'VG_28xx',
I don't think this should be here since VG_28xx doesn't have preview images

2021-08-24 18:37 UTC, rfrenchseti commented on opus/import/config_data.py
> +    'VGRSS':     'VG',
Move VGRSS after VGPPS for alphabetical order

2021-08-24 18:37 UTC, rfrenchseti commented on opus/import/config_data.py
> +    'VGRSS':       'Voyager RSS',
Move VGRSS after VGPPS for alphabetical order

2021-08-24 18:37 UTC, rfrenchseti commented on opus/application/apps/help/templates/help/gettingstarted.html
>                  occultation profiles.</li>
Say "occultation and reflectance profiles"

2021-08-24 18:37 UTC, rfrenchseti commented on opus/application/apps/paraminfo/models.py
> +                            and not referred):
"and not referred" should be indented under "pretty_name"

2021-08-28 06:25 UTC, juzen2003 commented
- Add tooltips for new opus types to internal_def_product_types.json
- Change "Ring/Limb Profile" to "Occultation and Reflectance Profiles"

2021-11-04 18:32 UTC, rfrenchseti commented
This pull has been integrated into #1183

2021-11-04 18:32 UTC, closed without merging