1166 detail short url
SETI/rms-opus pull request #1177
Opened 2021-07-13 23:39 UTC by dstopp

- Fixes #1166
- Were any Django, import pipeline, table_schema, or dictionary files modified? N
  - If YES:
    - Database used: opus3_test_210526
    - All Django tests pass: NA
    - FLAKE8 run on modified code: NA
- Were any JavaScript or CSS files modified? Y
  - If YES:
    - JSHINT run on all affected files: Y/NA
    - Tested on Chrome, Firefox, Safari, Edge, and iOS: Y/NA
      (Remember to test all browser sizes)
    - Tested for race conditions (with delayed API calls if applicable): Y/NA

Description of changes:

Known problems:

2021-07-14 19:16 UTC, juzen2003 requested changes
Issues:
- The perfect scrollbar on the detail page is not scrolling, it will show up at the beginning but will be gone once we start to scroll.
- When share button is clicked, the URL will change to the short one and if we refresh the page, the URL will go back to the long one (but we still stay in the detailed tab), not quite sure if this is what we expect.
- Similar to previous one, this exists in previous pull, not related to the changes here. When the cart button is clicked in detailed page, URL will change and if we refresh the page, the page will reload to search tab.

2021-07-14 20:59 UTC, rfrenchseti commented
Both of those last two are definitely bugs. I thought we had found and fixed that second one in the production version but I guess not. Please go ahead and fix it as well.

2021-07-19 19:28 UTC, juzen2003 requested changes
- Database used: opus3_test_210526
- All Django tests pass: Y
- JSHINT run on all affected files: Y
- FLAKE8 run on all affected files: Y
- Tested on Chrome, Firefox, Safari, and iOS: Y
  (Remember to test all browser sizes)
- Tested for race conditions (with delayed API calls if applicable): Y

Only one minor cleanup needed, please add ";" at the end of line 45 in detail.js

2021-07-19 19:28 UTC, juzen2003 commented on opus/application/static_media/js/detail.js
> +                            .catch(() => o_detail.showShareMessage("Error copying URL"))
miss `;` at the end

2021-07-19 20:28 UTC, juzen2003 approved these changes

2021-07-19 21:47 UTC, merged