1026 allow subcategories for inst names
SETI/rms-opus pull request #1229
Opened 2022-04-28 19:40 UTC by juzen2003

- Fixes #1026 
- Were any Django, import pipeline, or table_schema files modified? Y
  - If YES:
    - Database used: re-import
    - All Django tests pass: Y
    - FLAKE8 run on modified code: Y
- Were any JavaScript or CSS files modified? Y (CSS)
  - If YES:
    - JSHINT run on all affected files: NA
    - Tested on Chrome, Firefox, Safari, Edge, and iOS: NA
      (Remember to test all browser sizes)
    - Tested for race conditions (with delayed API calls if applicable): NA
- Was the documentation reviewed for necessary changes or additions? NA
  - About
  - Getting Started
  - FAQ
  - API Guide
  - Tooltips

Description of changes:
- Group ground based instruments into a subcategory ""Ground-based" in instrument widget.
- Add "Ground-based" to the mult_options of instrument_id field in obs_general.json.
- Update the logic to handle Django form when there is a mix of grouping and non-grouping checkboxes.

2022-05-05 20:31 UTC, juzen2003 commented
Progress of cleaning up the code related to mult table
- Changes:
    - Remove the usage of ```mult_target_name_template.json```
    - Remove ```MULT_TABLES_WITH_TARGET_GROUPING```
    - Add grouping & grouping_disp_order columns to all mult tables
        - Update all ```mult_options``` in .json files
        - We can set disp_order and group_disp_order in mult_options
    - Remove ```grouping_target_name``` table
    - Remove ```ZZGroupingTargetName``` in ```search/models.py```
    - Remove ```GroupingTargetName``` in ```metadata/models.py```
    - For mult tables with preprogrammed options:
        - add grouping column to store the group names
        - add group_disp_order column to store the group order
    - For mult from field_* functions:
        - We return either a string or a dictionary with this structure:
        ```
            {
                'col_val': value for the mult option, 
                'disp_name': display name on the UI,
                'disp_order': display order of this option within the same group, could be None
                'grouping': group name associated with this value, could be None
                'group_disp_order': display order of this group, could be None
            }
        ```
        - if disp_order or group_disp_order is not specify, they will be ordered alphabetically
    - Update the following mult field functions:
        - In ```obs_general.py```
            - ```field_obs_general_target_name```
            - ```field_obs_general_target_class```
        - In ```obs_instrument_ebrocc.py```:
            - ```field_obs_general_target_name```
            - ```field_obs_profile_quality_score```
            - ```field_obs_profile_source```
            - ```field_obs_profile_host```

**NOTE:**
    - For now only the ebrocc is updated, please import just the ebrocc volume. Errors will be raised if other instrument is imported.
**Possible issue:**
    - For non-preprogrammed mult, if we want to specify display order or group display order, we have to know all the possible options. For now, we use ```TARGET_NAME_GROUP_MAPPING``` in ```config_targets.py``` to specify the order and display name of different groups for non-preprogrammed mult. Previously we store the info in the db. Do we want to keep this info in db (then it will be like the old ```grouping_target_name``` table existing for display order only)? Or should we keep all the customized grouping info in another file?

2022-05-17 14:55 UTC, juzen2003 commented
- Update the field_.* functions with GROUP/TARGETS form type to call ```_create_mult```
- Update mult_options in these table schemas:
        - obs_general.json
        - obs_instrument_cocirs.json
        - obs_instrument_coiss.json
        - obs_instrument_couvis.json
        - obs_instrument_covims.json
        - obs_instrument_gossi.json
        - obs_instrument_nhlorri.json
        - obs_instrument_nhmvic.json
        - obs_instrument_vgiss.json
        - obs_mission_cassini.json
        - obs_mission_galileo.json
        - obs_mission_hubble.json
        - obs_profile.json
        - obs_wavelength.json
        - obs_type_image.json

2022-05-19 19:25 UTC, rfrenchseti requested changes

2022-05-19 19:25 UTC, rfrenchseti commented on opus/import/config_targets.py
> +# TODO: this grouping info is needed when we want to specify the order and
This comment can be removed

2022-05-19 19:25 UTC, rfrenchseti commented on opus/import/main_opus_import.py
> +        # if impglobals.ARGUMENTS.create_grouping_target_name:
Remove. Also delete do_grouping_target_name.py. Remove the --create-grouping-target-name option from main_opus_import and also remove all references to that argument from other argument help strings.

2022-05-19 19:25 UTC, rfrenchseti commented on opus/import/obs_base.py
> +    def _create_mult(
Change to put arguments on first line for consistency:
```
def _create_mult(self, col_val, col_class=None, disp_name=None,
                 disp_order=None, grouping=None, group_disp_order=None):
```

2022-05-19 19:25 UTC, rfrenchseti commented on opus/import/obs_base.py
> +        self, col_val, col_class=None, disp_name=None,
Is `col_class` used for anything? If not, remove everywhere.

2022-05-19 19:25 UTC, rfrenchseti commented on opus/application/apps/search/models.py
> +    grouping = models.CharField(max_length=20, blank=True, null=True)
Fix grouping and grouping_disp_order to be the same

2022-05-19 19:25 UTC, rfrenchseti commented on opus/import/obs_general.py
> +        data_dict = self._create_mult(
Collapse onto fewer lines, and you can just return directly instead of creating data_dict first.

2022-05-19 19:25 UTC, rfrenchseti commented on opus/import/obs_instrument_cassini_occ.py
> +        data_dict = self._create_mult(
Make more compact

2022-05-19 19:25 UTC, rfrenchseti commented on opus/import/obs_instrument_corss_occ.py
> +        data_dict = self._create_mult(
Make compact and put with return statement directly

2022-05-19 19:25 UTC, rfrenchseti commented on opus/import/obs_instrument_corss_occ.py
> +        data_dict = self._create_mult(
Make compact and put with return statement directly

2022-05-19 19:25 UTC, rfrenchseti commented on opus/import/obs_instrument_corss_occ.py
> +        data_dict = self._create_mult(
Make compact and put with return statement directly

2022-05-19 19:25 UTC, rfrenchseti commented on opus/import/obs_instrument_couvis_covims_occ.py
> +        data_dict = self._create_mult(
Make compact and put with return statement directly

2022-05-19 19:25 UTC, rfrenchseti commented on opus/import/obs_instrument_covims.py
> +        data_dict = self._create_mult(
Make compact and put with return statement directly

2022-05-19 19:25 UTC, rfrenchseti commented on opus/import/obs_instrument_ebrocc.py
> +from config_targets import *
We don't want to use "import *" anymore - list the specific things you need

2022-05-19 19:25 UTC, rfrenchseti commented on opus/import/obs_instrument_ebrocc.py
> +        data_dict = self._create_mult(
Make more compact.

2022-05-19 19:25 UTC, rfrenchseti commented on opus/import/obs_instrument_ebrocc.py
> +        data_dict = self._create_mult(
Make more compact. Also is this necessary. Doesn't "UNASSIGNED" automatically display as "Unassigned"? Original code might be unnecessary.

2022-05-19 19:25 UTC, rfrenchseti commented on opus/import/obs_instrument_ebrocc.py
> +        data_dict = self._create_mult(
Make compact and combine with return

2022-05-19 19:25 UTC, rfrenchseti commented on opus/import/obs_instrument_ebrocc.py
> +        data_dict = self._create_mult(
Make compact and combine with return

2022-05-19 19:25 UTC, rfrenchseti commented on opus/import/obs_instrument_ebrocc.py
> +            col_val=insthost,
This would be a good place to have something like self._create_mult_keep_case(insthost)

2022-05-19 19:25 UTC, rfrenchseti commented on opus/import/obs_instrument_hststis.py
> +        obs_type = self.field_obs_general_observation_type()['col_val']
This looks kind of ugly now. Perhaps we need a function `_observation_type` (put right above `field_obs_general_observation_type`) that does the work of the old `field_obs_general_observation_type` and just returns the raw value. That could be used in this function. Then the full `field_obs_general_observation_type` could call `_observation_type` and turn it into a mult with no additional work needed.

2022-05-19 19:25 UTC, rfrenchseti commented on opus/import/obs_instrument_vg28xx_vgrss.py
> +        return (self.field_obs_general_target_name()['col_val']
This can go back to being one line

2022-05-19 19:25 UTC, rfrenchseti commented on opus/import/obs_mission_cassini.py
> +            data_dict = self._create_mult(
One line, combine with return

2022-05-19 19:25 UTC, rfrenchseti commented on opus/import/obs_surface_geometry_name.py
> +        data_dict = self._create_mult(
Make one line and combine

2022-05-19 19:25 UTC, rfrenchseti commented on opus/import/table_schemas/mult_template.json
> +        "field_type": "char20",
Make 100

2022-05-19 19:25 UTC, rfrenchseti commented on opus/import/table_schemas/mult_template.json
> +        "field_notnull": false
Fix null

2022-05-19 19:25 UTC, rfrenchseti commented on opus/import/obs_instrument_vg28xx_vgrss.py
> +        data_dict = self._create_mult(
Combine

2022-05-23 18:04 UTC, juzen2003 commented
Updated based on above comments

2022-05-23 18:16 UTC, rfrenchseti requested changes
Just a few minor stylistic changes. I'm running a full-database import to make sure there aren't any surprises.

2022-05-23 18:16 UTC, rfrenchseti commented on opus/import/obs_general.py
> +        if target_name['col_val'] is None:
Shoudn't this use the new `_target_name`?

2022-05-23 18:16 UTC, rfrenchseti commented on opus/import/obs_instrument_couvis.py
> +        planet_id = self._cassini_planet_id()
Can make one line

2022-05-23 18:16 UTC, rfrenchseti commented on opus/import/obs_instrument_coiss.py
> +        planet_id = self._cassini_planet_id()
Can be one line

2022-05-23 18:16 UTC, rfrenchseti commented on opus/import/obs_instrument_covims.py
> +        planet_id = self._cassini_planet_id()
Can be one line

2022-05-23 18:16 UTC, rfrenchseti commented on opus/import/obs_instrument_hstacs.py
> +        obs_type = self._observation_type()
Can be one line

2022-05-23 18:16 UTC, rfrenchseti commented on opus/import/obs_instrument_hststis.py
> +        obs_type = self._observation_type()
Can be one line

2022-05-23 18:16 UTC, rfrenchseti commented on opus/import/obs_instrument_hstwfc3.py
> +        obs_type = self._observation_type()
Can be one line

2022-05-23 18:16 UTC, rfrenchseti commented on opus/import/obs_instrument_hstnicmos.py
> +        obs_type = self._observation_type()
Can be one line

2022-05-23 18:16 UTC, rfrenchseti commented on opus/import/obs_instrument_hstwfpc2.py
> +        obs_type = self._observation_type()
Can be one line

2022-05-23 18:16 UTC, rfrenchseti commented on opus/import/obs_instrument_vg28xx.py
> +        mission_phase = self._mission_phase_name()
Can be one line

2022-05-23 18:16 UTC, rfrenchseti commented on opus/import/obs_instrument_vg28xx.py
> +        mission_phase = _VG_TARGET_TO_MISSION_PHASE_MAPPING[target_name]
Can be one line

2022-05-23 18:16 UTC, rfrenchseti commented on opus/import/obs_instrument_vg28xx_vgpps_vguvs.py
> +        occ_dir = self._index_col('RING_OCCULTATION_DIRECTION')[0]
Can be one line

2022-05-23 18:16 UTC, rfrenchseti commented on opus/import/obs_instrument_vg28xx_vgpps_vguvs.py
> +        occ_flag = self._supp_index_col('PLANETARY_OCCULTATION_FLAG')
Can be one line

2022-05-23 18:16 UTC, rfrenchseti commented on opus/import/obs_instrument_vg28xx_vgpps_vguvs.py
> +        return self._create_mult(host)
Can be one line

2022-05-23 18:16 UTC, rfrenchseti commented on opus/import/obs_instrument_vgiss.py
> +        mission_phase = self._mission_phase_name()
Can be one line

2022-05-23 18:16 UTC, rfrenchseti commented on opus/import/obs_mission_cassini.py
> +        return self._create_mult_keep_case(rev_no)
Can be one line

2022-05-23 18:16 UTC, rfrenchseti commented on opus/import/obs_mission_cassini.py
> +        return self._create_mult(prime_inst_id)
Can be one line

2022-05-23 18:16 UTC, rfrenchseti commented on opus/import/obs_mission_hubble.py
> +        return self._create_mult(planet_id)
Can be one line

2022-05-24 00:04 UTC, juzen2003 commented on opus/import/obs_general.py
> +        if target_name['col_val'] is None:
Work in progress, need to override ```_take_name``` for instrument that doesn't derive target name from index file (```self._some_index_or_label_col('TARGET_NAME')```)

2022-05-24 03:25 UTC, juzen2003 commented on opus/import/obs_general.py
> +        if target_name['col_val'] is None:
Fixed.

2022-05-24 03:30 UTC, juzen2003 commented
Updated based on the latest comments.

2022-05-25 23:51 UTC, juzen2003 commented
- Group HST filter by instrument names.
- Group HST aperture type by instrument names.
- Group part of OCC receiver host by DSNs and Ground-based Telescopes.
- Group part of OCC signal source by Stars

2022-05-30 23:57 UTC, rfrenchseti approved these changes

2022-05-30 23:58 UTC, merged