Remove caching of api/fields due to memcached size limit
SETI/rms-opus pull request #1296
Opened 2023-02-14 18:32 UTC by rfrenchseti

- Fixes #1294 
- Were any Django, import pipeline, or table_schema files modified? Y
  - If YES:
    - Database used (or new import): opus3_test_221201
    - FLAKE8 run on modified code: Y
    - All Django tests pass: Y
    - Code coverage run and still at 100%: Y
- Were any JavaScript or CSS files modified? N
  - If YES:
    - JSHINT run on all affected files: Y/NA
    - Tested on Chrome, Firefox, Safari, Edge, and iOS: Y/NA
      (Remember to test all browser sizes)
    - Tested for race conditions (with delayed API calls if applicable): Y/NA
- Was the documentation reviewed for necessary changes or additions? NA
  - About
  - Getting Started
  - FAQ
  - API Guide
  - Tooltips
  - Import/database schema

Description of changes:

memcached has a 1MB limit on cached data, which we now exceed when returning /api/fields.json with a full database (but not with a test database). Caching has been removed for this API call and the relevant tests have also been removed.

Known problems:

/api/fields is now slower...

2023-02-15 20:42 UTC, rfrenchseti commented
This branch is now running on the production server and successfully solved the problem with the log analyzer crashing.

2023-02-23 22:51 UTC, juzen2003 requested changes
- Database used: re-import
- All Django tests pass: Y
- JSHINT run on all affected files: NA
- FLAKE8 run on all affected files: Y
- Code coverage run: Y
- Tested on Chrome, Firefox, Safari, and iOS: NA
  (Remember to test all browser sizes)
- Tested for race conditions (with delayed API calls if applicable): NA

Note: only three minor code style issues need to be cleaned up.

2023-02-23 22:51 UTC, juzen2003 commented on opus/application/apps/metadata/views.py
> +                                            allow_units_override=False)
Remove one extra space

2023-02-23 22:51 UTC, juzen2003 commented on opus/application/apps/metadata/views.py
> +                                                            '<TARGET>')
This can be one line, or remove the extra spaces if staying multiple lines.

2023-02-23 22:51 UTC, juzen2003 commented on opus/application/apps/metadata/views.py
> +            form_type_unit_id) = parse_form_type(f.form_type)
remove extra spaces

2023-02-23 23:09 UTC, rfrenchseti commented on opus/application/apps/metadata/views.py
> +                                            allow_units_override=False)
Fixed

2023-02-23 23:09 UTC, rfrenchseti commented on opus/application/apps/metadata/views.py
> +                                                            '<TARGET>')
Fixed

2023-02-23 23:09 UTC, rfrenchseti commented on opus/application/apps/metadata/views.py
> +            form_type_unit_id) = parse_form_type(f.form_type)
Fixed

2023-02-24 17:12 UTC, juzen2003 approved these changes

2023-02-24 17:29 UTC, merged