About, FAQ, cart removerange, cleanup
SETI/rms-opus pull request #664
Opened 2019-05-07 19:26 UTC by rfrenchseti

- Clean up About box
- Clean up and add FAQs
- Remove tutorial
- Change OPUS logo to OPUS3
- Disable addrange and addall for view=cart
- Implement removerange for view=cart
- Add new cart tests
- Fix bug in normalizeurl caught by about page(!) and add test
- Clean up bad JS

Fixes H049, H038, and #615

2019-05-07 20:17 UTC, dstopp requested changes

2019-05-07 20:17 UTC, dstopp commented on opus/application/apps/help/templates/help/about.html
>  <table border="1">
From the html documentation: The border attribute of <table> is not supported in HTML5. Use CSS instead.  I know you didn't change this, but it should probably be addressed.

2019-05-08 04:46 UTC, rfrenchseti commented
- I fixed the About CSS issue.
- I updated the browser versions to be the ones that support MutationObserver.
- I changed the loop to use for ... of.
- I found one other instance of "for ... in" in cart.js and realized the code surrounding it made very little sense. I rewrote getDownloadFiltersChecked to be sane.
- I fixed the bad indentation in cart.js (you probably want to compare with whitespace off).

2019-05-08 06:10 UTC, dstopp approved these changes

2019-05-08 16:01 UTC, merged