C035 cart
SETI/rms-opus pull request #677
Opened 2019-05-13 00:22 UTC by dstopp

c035 - add support for PS and infinite scroll to cart; added the table view whilst i was at it.

2019-05-13 00:47 UTC, rfrenchseti commented
1) Clicking on a table row doesn't bring up the metadata modal
2) Unchecking an obs in the table view doesn't actually seem to do anything
3) Shift+clicking on a table row doesn't start add range
4) If you click on the Cart tab while already in the cart view, you get a blank gallery
5) Now that we have "View Gallery/Table" and then "Select Metadata" in the nav bar, it has a very similar feel to the browse page. *Except* those items are on the right side of a divider, and the whole section is on the right side of the screen. What do you think about:
    - A) Swapping the two sides (View Table / Select Metadata / Empty Cart) and (Metadata CSV / Data Archive / URL archive) and/or
    - B) Swapping the product pane and the gallery pane. If we did this, then switching between browse and cart would seem almost seamless. The nav bar wouldn't change all that much. In fact we could rename Download CSV (all results) to Download CSV (cart) and it would also look almost the same. You could even keep the slider where it is (since we do want a slider in the cart)
6) There's something really broken with infinite scroll on the normal browse page. As you scroll down it keeps reloading the same page over and over so you get duplicate data, and the slider moves right and then jumps left.
7) The cart gallery runs off the bottom of the screen, so when it's full the final row of thumbnails is partially obscured.

2019-05-14 01:36 UTC, rfrenchseti commented
- I had to change document.ready to say:
`    opus.namespaceDict = { "search": o_browse, "cart": o_cart, "browse": o_browse };`
I'm sure this isn't the right fix, but at least it let me get things going.
- When you first switch to the browse page, the slider just spins forever
- If you drag the slider on the browse page, it does update and the page fetches, but the size of the slider "button" is wrong - it doesn't expand to support the width of the observation number you've set
- When you scroll down in either gallery or table view on the browse page, there is no big spinner while it fetches
- When you switch from gallery to table and back on the browse page, the slider moves
- The first time you switch to the Cart tab, it says there are no entries in the cart. Then if you switch to it again it displays thumbnails. Although if you click it yet again the thumbnails go away and you can't get them back.
- Clicking on a table header (browse or cart) jumps you back to the search tab
- Infinite scroll on the browse tab is still completely broken - as you scroll down you keep getting copies of the same data
- Infinite scroll on the cart gallery doesn't do anything at all

2019-05-14 01:56 UTC, rfrenchseti requested changes

2019-05-14 01:56 UTC, rfrenchseti commented on opus/application/static_media/js/browse.js
> +        let selector = (opus.prefs[browse] === "gallery") ?  `#${opus.prefs.view} .gallery .thumbnail-container` : `#${opus.prefs.view} .op-data-table tbody tr`;
I don't see how this can work. Isn't `browse` an undefined variable here? Maybe this is why the slider isn't working some of the time.

2019-05-14 01:56 UTC, rfrenchseti commented on opus/application/apps/ui/templates/base.html
> +                                    <a href="#" class="op-metadataModal nav-link" data-toggle="modal" data-target="#metadataSelector" title="Select metadata to display or include in CSV files for eac
I think we should be calling this op-metadata-modal.

2019-05-14 01:56 UTC, rfrenchseti commented on opus/application/static_media/js/browse.js
> +        let browse = (opus.prefs.view === "cart_" ? "cart_browse" : "browse");
This should not have a "_" after cart

2019-05-14 01:56 UTC, rfrenchseti commented on opus/application/static_media/js/browse.js
> +        let browse = (opus.prefs.view === "browse" ? "browse" : "cart_browse");
This `let browse =` is duplicated many times. We should have a function for it.

2019-05-14 01:56 UTC, rfrenchseti commented on opus/application/static_media/js/browse.js
> +            $(".op-dataTable-view", tab).hide();
Shouldn't this be `op-data-table-view` to match `op-data-table`?

2019-05-14 01:56 UTC, rfrenchseti commented on opus/application/static_media/js/browse.js
>          let tab = `#${opus.prefs.view}`;
I thought we were going to abstract this away so that opus.prefs.view was not used directly as a selector.

2019-05-14 01:56 UTC, rfrenchseti commented on opus/application/static_media/js/opus.js
> +    opus.namespaceDict = { "cart": o_cart, "browse": o_browse };
If this maps "view" to namespace, I think it should have a name that reflects that. Like viewToNamespaceDict.

2019-05-14 02:00 UTC, rfrenchseti commented
The following bugs from earlier are now FIXED:

1) Clicking on a table row doesn't bring up the metadata modal
2) Unchecking an obs in the table view doesn't actually seem to do anything
3) Shift+clicking on a table row doesn't start add range

2019-05-15 00:17 UTC, juzen2003 commented
mutationObserver.js looks fine. cartObserver will detect changes when we: 
- Switch from other tabs to cart tab 
- In gallery, click add/remove icon
- In table, click checkbox, remove/add tab in hamburger
- Switch between gallery and table
- adjustProductInfoHeight is called in cartObserver callback function to update both perfect scrollbar.
The only optimization I can see is to update the callback with: (which I didn't do it in original file)              
`let lastMutationIdx = mutationsList.length - 1;
mutationsList.forEach((mutation, idx) => {
    if (idx === lastMutationIdx) {
        adjustProductInfoHeight();
    }
});`
But overall it will work fine.

2019-05-16 18:29 UTC, rfrenchseti requested changes

2019-05-16 18:29 UTC, rfrenchseti commented on opus/application/static_media/js/browse.js
>          let tab = opus.getViewTab();
countGalleryImages needs to take a tab argument like everything else.

2019-05-16 18:29 UTC, rfrenchseti commented on opus/application/static_media/js/browse.js
> +        opus.getViewNamespace(view).galleryBoundingRect = o_browse.countGalleryImages();
Note that countGalleryImages uses the "current" opus.prefs.view tab, while the rest of this function uses the view that was passed in. countGalleryImages needs to take a tab argument as well.

2019-05-16 18:29 UTC, rfrenchseti commented on opus/application/static_media/js/browse.js
> +        if (limitNum === 0) {
Remove debugging code eventually.

2019-05-16 18:29 UTC, rfrenchseti commented on opus/application/static_media/js/browse.js
updateStartobsInUrl is using the current opus.prefs.view. It needs to use the passed-in tab.

2019-05-16 18:29 UTC, rfrenchseti commented on opus/application/static_media/js/browse.js
>          let limitNum = customizedLimitNum === undefined ? o_browse.getLimit() * 2 : customizedLimitNum;
getLimit() needs to take the tab as an argument

2019-05-16 18:29 UTC, rfrenchseti commented on opus/application/static_media/js/browse.js
> +        opus.getViewNamespace(view).galleryBoundingRect = o_browse.countGalleryImages();
getLimit() below throughout the path function (many instances) needs to take a tab argument

2019-05-16 18:29 UTC, rfrenchseti commented on opus/application/static_media/js/browse.js
> +        opus.getViewNamespace(view).galleryBoundingRect = o_browse.countGalleryImages();
also getViewNamespace needs to take a tab argument

2019-05-16 18:29 UTC, rfrenchseti commented on opus/application/static_media/js/browse.js
> +        let xCount = Math.floor(width/o_browse.imageSize);   // images are 100px
Probably want to kill the comment giving a hard value for the image size

2019-05-16 18:29 UTC, rfrenchseti commented on opus/application/static_media/js/browse.js
> +    calculateGalleryWidth: function() {
calculateGalleryWidth and Height need to take tab arguments

2019-05-17 01:01 UTC, rfrenchseti requested changes

2019-05-17 01:01 UTC, rfrenchseti commented on opus/application/static_media/js/browse.js
> +            topBoxBoundary = topBoxBoundary ||
Add extra level of parens around expression

2019-05-17 01:01 UTC, rfrenchseti commented on opus/application/static_media/js/browse.js
> +    maxCachedObservations: 750,    // max number of obserations to store in cache;
obserations => observations

2019-05-17 01:01 UTC, rfrenchseti commented on opus/application/static_media/js/browse.js
> +        // remove any existing view= slug or startobs= slug
Remove or startobs= slug

2019-05-17 01:08 UTC, rfrenchseti approved these changes

2019-05-17 01:08 UTC, merged