Fix the issue of the missing (i) icon next to qtype in search widgets (issue #827)
SETI/rms-opus pull request #830
Opened 2019-07-25 18:27 UTC by juzen2003

- Fixes #827 
- Local branch: tooltip_issue_for_any_all_only_827
- Use the same popover method for the hover over event on (i) icon next to qtype.

2019-07-26 21:24 UTC, dstopp requested changes

2019-07-26 21:24 UTC, dstopp commented on opus/application/static_media/js/widgets.js
> +            if ($(`#widget__${slug} select[name="${qtype}"]`).length !== 0) {
What do you think about combining the previous 'if' block and just do all the "${qtype}" business together?

2019-07-26 21:24 UTC, dstopp commented on opus/application/apps/ui/templates/ui/base.html
> +    <div id="op-range-qtype-helper-html">
What do you think of renaming the id to "op-qtype-tooltip" instead?  I'm not clear that we need 'helper' or 'html' in that name and my thought is that this is just the tooltip for the qtype.

2019-07-27 01:20 UTC, juzen2003 commented
- Update based on Debby's comments.

2019-07-28 21:10 UTC, dstopp approved these changes

2019-07-29 16:17 UTC, merged