738 allow selection across cache boundaries
SETI/rms-opus pull request #835
Opened 2019-07-30 22:44 UTC by dstopp

-on start of select range, pop up overlay with range start information
-allow selection of observations in range to span across cached data
-make sure range selection works in both directions

2019-07-31 04:56 UTC, rfrenchseti requested changes
- I think the popup should distinguish between "Add range to cart starting at observation #x: opusid" and "Remove range from cart starting at observation #x: opusid". Just plain "Range select start" doesn't explain that it's a cart operation in progress. The wording given here matches that in the hamburger menu, and the format #x: yyy matches the hover text.
- When you start an add range and then drag the slider to a different cache region, the new thumbnail hamburger menus say "start add range" instead of "end add range".
- Now that we can add lots of observations, several bugs have been revealed that were probably there before but need to be fixed:
  - If adding the range fails because it exceeds the maximum number, the UI still selects the thumbnails even though the backend won't have added them to the cart. We need to wait for the addrange.json to return with a success code before changing the thumbnails. This will also solve the "no spinner" problem commented on around line 315 (which is not the same spinner problem mentioned below here).
  - When add.json or addrange.json returns with a failure code and an error dialog box pops up, the browse tab slider position is reset to 1 for no obvious reason.
  - When there are a lot of items in the cart and you switch to the cart tab, there is no spinner while it's loading the data until the very end (there's a long pause before the spinner starts)
- Another bug I noticed at the same time if you feel like fixing it here: If you pull down a hamburger menu and then move the slider, the hamburger menu stays present on the screen. The same is true of scrolling. Once this happens things get very confused if you start a range - the slider jumps.

2019-08-27 22:54 UTC, rfrenchseti requested changes
- When adding a range the little window as "Add range from cart" instead of "Add range to cart". The hamburger menu says this too.
- The "loading" spinner needs to have a delay on it just like the cart badge spinners do (see showCartCountSpinner). Right now every time you click on a trashcan/cart icon, you get a flicker of the big spinner even if it returns really fast.
- You need to look at updateBadges. I think its whole purpose is gone now that we don't need to add items to the cart one at a time when doing an addrange.

2019-08-27 22:54 UTC, rfrenchseti commented on opus/application/apps/ui/templates/ui/base.html
> +
Does this have the wrong indent level?

2019-08-27 22:54 UTC, rfrenchseti commented on opus/application/static_media/js/cart.js
> +        // just so we don't have to continually checke for both addrange and add...
"checke"

2019-08-27 22:54 UTC, rfrenchseti commented on opus/application/static_media/js/cart.js
> +            let toELem = $(`${tab} .op-gallery-view`).find(`[data-obs=${toObsNum}]`);
ELem should not have a capital L

2019-08-27 22:54 UTC, rfrenchseti commented on opus/application/static_media/js/cart.js
> +        if (toOpusId != undefined) {
!==

2019-08-27 22:54 UTC, rfrenchseti commented on opus/application/static_media/js/cart.js
> +            // note - doing it this way handles the obs on the browse tab at the same time
What does "this way" mean?

2019-08-27 22:54 UTC, rfrenchseti commented on opus/application/static_media/js/cart.js
> +        }
I think it would be more clear what's going on if we set "length = 1" here rather than using the default at the top of the function.

2019-08-27 22:54 UTC, rfrenchseti commented on opus/application/static_media/js/cart.js
> +            }
I think it would be more clear what's going on if we set "fromIndex = 0" here rather than using the default at the top of the function.

2019-08-27 22:54 UTC, rfrenchseti commented on opus/application/static_media/js/cart.js
> +        let length = 1;
See comments below...could set length and fromIndex to undefined or null or something here to enforce their setting below and avoid potential bugs.

2019-08-27 23:14 UTC, dstopp commented on opus/application/apps/ui/templates/ui/base.html
> +
ok, looks like my editor is dropping tabs instead of spaces or something.  fixed.

2019-08-27 23:16 UTC, dstopp commented on opus/application/static_media/js/cart.js
> +        // just so we don't have to continually checke for both addrange and add...
done

2019-08-27 23:17 UTC, dstopp commented on opus/application/static_media/js/cart.js
> +            let toELem = $(`${tab} .op-gallery-view`).find(`[data-obs=${toObsNum}]`);
at least it was consistent :)  

done.

2019-08-27 23:17 UTC, dstopp commented on opus/application/static_media/js/cart.js
> +        if (toOpusId != undefined) {
done

2019-08-27 23:19 UTC, dstopp commented on opus/application/static_media/js/cart.js
> +            // note - doing it this way handles the obs on the browse tab at the same time
removed comment, no longer applicable

2019-08-27 23:20 UTC, dstopp commented on opus/application/static_media/js/cart.js
> +        }
ok

2019-08-27 23:21 UTC, dstopp commented on opus/application/static_media/js/cart.js
> +            }
ok

2019-08-28 16:20 UTC, rfrenchseti commented
The following comments have not been addressed:

- When adding a range the little window as "Add range from cart" instead of "Add range to cart". The hamburger menu says this too.
- You need to look at updateBadges. I think its whole purpose is gone now that we don't need to add items to the cart one at a time when doing an addrange.

2019-08-28 16:54 UTC, rfrenchseti requested changes
The following comments have not been addressed:

- When adding a range the little window as "Add range from cart" instead of "Add range to cart". The hamburger menu says this too.
- You need to look at updateBadges. I think its whole purpose is gone now that we don't need to add items to the cart one at a time when doing an addrange. Please remove it.

Also:

- When disabling clicking during cart operations, it only disables the gallery thumbnail area. You can still click on tab names. Is this the desired behavior?
- You can still Ctrl+click on an item in the cart tab (gallery or table) and have it add/remove from the cart. This needs to be disabled as well.

2019-08-28 16:54 UTC, rfrenchseti commented on opus/application/static_media/js/browse.js
> +    pageLoaderSpinnerTimer: null,   // used to apply a small delay to the loader on cart edit
This delay occurs in lots of places, not just on cart edit

2019-08-28 16:54 UTC, rfrenchseti commented on opus/application/static_media/js/browse.js
> +            let addRemoveText = (rangeSelected === "removerange" ? "remove range from" : "add range from");
Here is where it should say "add range to"

2019-08-28 16:54 UTC, rfrenchseti commented on opus/application/static_media/js/browse.js
> +            let addRemoveText = (inCart !== "in" ? "remove range from" : "add range from");
And here

2019-08-28 16:54 UTC, rfrenchseti commented on opus/application/static_media/js/browse.js
> +        $(`${tab} .op-range-select-info-box`).html(`${actionText} range from cart starting at observation #${obsNum} ${opusId}  (ESC to cancel)`).addClass("op-range-select");
Also needs to change "from"/"to" here

2019-08-28 16:54 UTC, rfrenchseti commented on opus/application/static_media/js/browse.js
> +            // This should always be true - we're just being careful
Actually I don't think this should always be true. For example, if you scroll such that the next page is being prefetched (spinner comes on), you can still click on a thumbnail to add it to the cart (also turns on spinner). Then when the page load is finished it turns off the spinner, and later when the cart operation returns it also tries to turn off the spinner, but the spinner is already off by then.

The right way to fix this is probably to reference count the on/off actions, since they should always be paired, and that way the spinner won't turn off until the last operation is complete. However, this sounds like a recipe for bugs, and it isn't a common occurrence, so I suggest we just remove this comment, perhaps put a new comment describing this issue, and forget about it for now.

2019-08-28 16:54 UTC, rfrenchseti commented on opus/application/static_media/js/cart.js
> +    getEditURL: function(opusId, action, updateBadges=true) {
Remove updateBadges

2019-08-28 16:54 UTC, rfrenchseti commented on opus/application/static_media/js/cart.js
> +        let updateBadges = true;
Remove updateBadges

2019-08-28 16:54 UTC, rfrenchseti commented on opus/application/static_media/js/cart.js
> +                if (updateBadges) {
Remove updateBadges

2019-08-28 16:56 UTC, rfrenchseti commented
Also I don't think this fully fixes #787 because it doesn't do anything about the potential reset.json problems.

2019-08-30 15:53 UTC, rfrenchseti approved these changes

2019-08-30 15:54 UTC, merged