Minor bugfix to remove trashcan from selectMetadata
SETI/rms-opus pull request #907
Opened 2019-11-23 01:11 UTC by dstopp

Fixes #724 (Remove trashcan when there is only one metadata column remaining)

Includes minor re-organization of file structure to isolate the files and data associated with the selectMetadata dialog out of browse.js and into selectMetadata.js.

2019-11-24 18:51 UTC, rfrenchseti requested changes
- Look into replacing "info" and "unselect" with op- names
- If you click on the top row trash can repeatedly as fast as you can, you easily get into a state where there is more than one line but all the trashcans are gone

2019-11-25 17:03 UTC, rfrenchseti commented
Also, can you only remove the trash can on the first item in the list? Right now you can see the icon on the second element disappear before the animation starts to remove the whole line and it looks awkward.

2019-11-26 21:40 UTC, dstopp commented
Issues address; also fixed a bug in widgets that caused menu items in select metadata to be highlighted when they were only present in widgets but not in select metadata

2019-11-27 04:08 UTC, rfrenchseti approved these changes

2019-11-27 04:09 UTC, merged