Issue 46 units selection
SETI/rms-opus pull request #929
Opened 2019-12-06 09:44 UTC by juzen2003

- Fixed #46 
- Merge pull request https://github.com/SETI/pds-opus/pull/891 as the base, and update from there.
- Run JSHint on: search.js, hash.js, and widgets.js
- Test on latest Chrome, FF, Opera, and Safari.
- Done Items:
    - Update unit- to opus.extras in the following cases: 
        - Open a widget and select a different value in qtype:
            - properly update opus.extras, unit should stay in unit- not qtype-
            - properly update opus.selections/selections, unit should stay in extras with unit- not selections
        - Properly add unit- in URL when open a widget
        - Properly remove unit- in URL when close a widget
        - Update unit- in URL when an input is added/remove 
        - Update unit- in URL when refreshing the page with multiple input in a widget 
        - Update unit- in URL when calling API (getHashStrFromSelections) 
        - Update unit- when page reloads (getHashStrFromSelections, initFromHash) 
    - Update hints when unit is changed.
    - No search will be performed if unit is changed when all input sets are empty, only hints will be updated.
    - No search will be performed if qtype is changed when corresponding input set is empty.

2019-12-08 23:34 UTC, rfrenchseti requested changes
- Nicely done. I only found one real issue and a handful of small code comments.
- Preprogrammed ranges have units associated with them. Right now they are ignored. But when the user selects a range, the UI needs to check if the ranges' unit is equal to the widget's currently selected unit. If not, and there are other input lines with values in them, there needs to be some kind of error dialog. If there are no other lines with values in them, then the widget's unit needs to be set appropriately.
- Unrelated to the current pull, but I notice whenever you create a new widget, there is a spinner in the header to the right of the title that comes on and eventually goes away, but I have no idea what it's spinning for. Nothing is being waiting on. The result count is good, the hints are good, etc. Maybe that spinner should go away?

2019-12-08 23:34 UTC, rfrenchseti commented on log_analyzer/opus/slug.py
> -                       'range', 'recyclebin', 'reqno', 'request', 'startobs', 'types', 'url_cols', 'view', 'widgets', 'widgets2',
There appears to be a merge error with this. The recyclebin and url_cols slugs need to stay in the list.

2019-12-08 23:34 UTC, rfrenchseti commented on opus/application/apps/ui/templates/ui/widget.html
> +                    <select class="unit-{{ slug }}" name="unit-{{ slug }}" tabindex="0">
Shouldn't these names of "op-" in front of them? And do we really need identical classes and IDs?

2019-12-08 23:34 UTC, rfrenchseti commented on opus/application/static_media/js/hash.js
>                          let numberOfQtypeInputs = encodedExtraValues.length;
Shouldn't this be just `numberOfInputs` or something since this can either be qtype or unit slug?

2019-12-08 23:34 UTC, rfrenchseti commented on opus/application/static_media/js/hash.js
> +                            if (unitSlug in opus.extras) {
This is kind of tricky. I finally figured out that "unitSlug" is empty if the main slug is already a unit slug, which is counter-intuitive. I think this needs some kind of comment here and line 177, or perhaps just above where unitSlug is first created.

2019-12-08 23:34 UTC, rfrenchseti commented on opus/application/static_media/js/hash.js
> +                            if (slugInExtrasVal[trailingCounter-1] !== null) {
Why is the "main" slug (whether qtype or unit) inserted directly using hash.push, but the associated unit slug, if any, is inserted by calling `updateHashFromExtras`? Shouldn't they be consistent?

2019-12-08 23:34 UTC, rfrenchseti commented on opus/application/static_media/js/hash.js
> +        hash = (hash.search("&") > -1 ? hash.split("&") : [hash]);
Comment before this function should say "qtype or unit"

2019-12-08 23:34 UTC, rfrenchseti commented on opus/application/static_media/js/hash.js
> +    syncUpWithOPUSSelectionsForWidgetsWithNoQtype: function(selections, extras, widgetSlug) {
I probably understood this function once, but I don't anymore. Can you elaborate in the comments why this function here and what it does? Under what circumstances is there a string/range widget but no qtype?

2019-12-08 23:34 UTC, rfrenchseti commented on opus/application/static_media/js/hash.js
> +    syncUpWithOPUSSelectionsForWidgetsWithNoQtype: function(selections, extras, widgetSlug) {
Also, below we check for qtype in extras. Do we also need to check for unit-? Is the name of the function correct?

2019-12-08 23:34 UTC, rfrenchseti commented on opus/application/static_media/js/hash.js
> +                if (slug.match(/qtype-.*/) || slug.match(/unit-.*/)) {
Better with startsWith?

2019-12-08 23:34 UTC, rfrenchseti commented on opus/application/static_media/js/search.js
> +                    case "RANGE":
I'm not sure why this wasn't done before, but the code after each "case" should be indented one level.

2019-12-08 23:34 UTC, rfrenchseti commented on opus/application/static_media/js/search.js
> +                while(units.length < numberOfInputSets) {
Space after while

2019-12-08 23:34 UTC, rfrenchseti commented on opus/application/static_media/js/widgets.js
> +        delete opus.extras[`unit-${slugNoNum}`];
Let's get rid of that line that says "z-". That's left over from some ancient feature we no longer support. Perhaps it was the old version of units? Before my time.

2019-12-08 23:34 UTC, rfrenchseti commented on opus/application/static_media/js/widgets.js
> +            let qtypeInputs = $(`#widget__${slug} .widget-main select[name="${qtype}"]`);
Should .widget-main be renamed to .op-widget-main?

2019-12-09 17:58 UTC, rfrenchseti requested changes
One more bug:
- The dropdown boxes are using the "internal" name for each unit (like "saturnradii") not the "display" name (like "Rs (71492)"). See opus_support.py for how the display names are encoded. The idea is the display name should show up to the user, but when the user selects it the internal name should be put in the unit-XXX slug.

2019-12-11 08:08 UTC, juzen2003 commented
- Update preprogrammed ranges info when unit is changed.
- Still tuning styling.

2019-12-11 15:44 UTC, rfrenchseti commented on log_analyzer/opus/slug.py
> -                       'range', 'recyclebin', 'reqno', 'request', 'startobs', 'types', 'url_cols', 'view', 'widgets', 'widgets2',
This has not been fixed.

2019-12-11 15:59 UTC, rfrenchseti requested changes
- When you change the units, the URL is updated with the current input values even if they are illegal. For example, type something bad in the ring radius "min" field. Exit the field and change the widget's unit to something else. Notice that the bad value is now in the URL.
- Look at the ring radius "thebe extension" when using "m" units and narrow the browser. The numbers are wide enough that they lay on top of the word "extension".
- How are you figuring out the number of decimal places to put when you change the units in the range dropdown? For example, in the wavelength widget, select "cm" and then type in a color name. It will just show "0.0" because there aren't enough digits available. Check out the function `adjust_format_string_for_units` in opus_support.py. It will automatically adjust a format string to the proper number of decimal places given the new units.

2019-12-13 01:52 UTC, rfrenchseti requested changes
- normalizeinput does not have the units passed, so the returned "pretty" value can have the wrong number of digits, resulting in the number being truncated incorrectly.

2019-12-13 01:52 UTC, rfrenchseti commented on opus/application/static_media/js/search.js
> +                        // but since we are opening the collpasible item here, to make sure all behaviors
collapsible spelled wrong here and below

2019-12-13 01:52 UTC, rfrenchseti commented on lib/opus_support.py
> +                'saturnradii':  ('Rs (60330)', 60330.),
Whoops. Good catch. But Jupiter should come before Saturn in the list. They are in order inner to outer planet.

2019-12-13 02:15 UTC, rfrenchseti commented
Test comment

2019-12-16 02:52 UTC, rfrenchseti requested changes
- There's a race condition with the new unit conversion. If you change units from A to B, and then change units again B to C before the first normalizeinput returns, the second call to normalizeinput gets called with unit=C, sourceunit=B but the numbers that get passed in are still in units of A. I'm not sure what the right way to fix this is. It seems like you should keep the units along with the numbers in the inputs, not just in the dropdown box. Then update the units in the inputs when normalizeinput successfully returns and you're updating the input contents.

2019-12-16 02:52 UTC, rfrenchseti commented on opus/application/apps/search/views.py
> +                        if is_sourceunit or sourceunit_val is not None:
Note the code starting at line 697. It catches exceptions during the execution of func() and prevents the back end from crashing. The new code calls func() when there’s a sourceunit without catching these. Also if there’s a sourceunit, func() gets called twice, once here and once inside the try. Not fatal if func is float or int, but bad if it’s something converting with a more complicated format. 

As much as I hate putting lots of code in a try block, I think the right thing to do is move the unit conversion a few lines down to just before the if pretty_results and use new_value instead of func(value_to_use).

2019-12-16 02:52 UTC, rfrenchseti commented on opus/application/static_media/js/search.js
> +            // Use this flag to determine if
Comment is truncated

2019-12-16 02:52 UTC, rfrenchseti commented on opus/application/static_media/js/search.js
>              if ($(this).attr("name").startsWith("qtype-")) {
The comment before this function should mention unit drop down too

2019-12-16 21:52 UTC, rfrenchseti requested changes
- Type in a value. Change the unit without otherwise leaving focus first. The value you just typed will not be converted.
- Something similar happens with preprogrammed ranges. Type in a range name. Click on the range. Change the units before normalizeinput returns. The value will be in the wrong units.

2019-12-17 22:01 UTC, merged