New API Guide and API Cleanup
SETI/rms-opus pull request #950
Opened 2020-01-06 02:41 UTC by rfrenchseti

- Fixes #915 (Need new API Guide). The API Guide has been completely rewritten. It now uses Markdown instead of the weird YAML thing we used to use.
- Fixes #942 (Need API call that returns all possible product types). There are new API calls `/api/product_types.json` and `/api/product_types/[opusid].json`.
- Fixes #647 (Results API: Cleanup needed). `api_get_images_by_size`, `api_get_images`, `api_get_image` have been cleaned up. No API calls use the old `response_formats` function and it has been deleted.
- Fixes #495 (Need V2 of files API that uses slug names instead of pretty names). The existing `/api/files` APIs have been changed to return the short name instead of the pretty name of product types. I did this instead of creating a new V2 version of the API because no one was using the files API anyway so it wouldn't break anything.
- Fixes #156 (API calls need to return startobs/limit/result_count metadata with each response). There is a new `available` field in some API returns that gives the result count in addition to the existing requested `limit` and actually returned `count`.
- There is a new feature that allows creation and download of a PDF file for many of the Help pane choices. It won't work on your computer unless you install `wkhtmltopdf` from https://wkhtmltopdf.org/  You must install a version with the Qt patches.
- Running tests on this branch requires the use of the new OPUS test database `opus3_test_200103`.

2020-01-06 02:42 UTC, rfrenchseti commented
Since you may not be able to create the PDF files on your own, here is what they look like:

[opus_api_guide.pdf](https://github.com/SETI/pds-opus/files/4024500/opus_api_guide.pdf)
[opus_volumes.pdf](https://github.com/SETI/pds-opus/files/4024501/opus_volumes.pdf)
[opus_faq.pdf](https://github.com/SETI/pds-opus/files/4024502/opus_faq.pdf)
[opus_getting_started.pdf](https://github.com/SETI/pds-opus/files/4024503/opus_getting_started.pdf)
[opus_about.pdf](https://github.com/SETI/pds-opus/files/4024504/opus_about.pdf)

2020-01-08 19:41 UTC, rfrenchseti commented
I made a mistake with renaming `STATIC_ROOT`. There are now two variables, `STATIC_ROOT` and `OPUS_STATIC_ROOT`. The first is ignored in a non-production environment (e.g. runserver). The second should be a pointer inside the OPUS source tree in a non-production environment, or the really static location in a production environment. See the comments in opus_template.py.

2020-01-25 02:25 UTC, juzen2003 requested changes
- Database used: opus3_test_200107
- All Django tests pass: Y
- JSHINT run on all affected files: Y (opus.js & search.js)
- Tested on Chrome, Firefox, Safari, and iOS: Y
  (Remember to test all browser sizes)
- Tested for race conditions (with delayed API calls if applicable): NA (run each api one at a time)

- Comment:
  - For the indentation issues in html, they look matched in atom but not in github file display. That's because regular 4 spaces look like 4 "." in atom, but the places with indentation issues have something like ">>" in atom.

2020-01-25 02:25 UTC, juzen2003 commented on opus/application/apps/help/templates/help/about.html
> +			<a href="https://tools.pds-rings.seti.org/opus/#/SURFACEGEOplutocenterresolution2=5.00000&SURFACEGEOplutophase1=160.000&surfacegeometrytargetname=Pluto&qtype-SURFACEGEOplutophase=any&cols=opusid,i
Need to update this later once pull https://github.com/SETI/pds-opus/pull/965 is merged.

2020-01-25 02:25 UTC, juzen2003 commented on opus/application/apps/help/api_guide.md
> +
For record, we have to update this later once pull #965 is merged.

2020-01-25 02:25 UTC, juzen2003 commented on opus/application/apps/help/api_guide.md
> +
Same here, might want to update the URL later.

2020-01-25 02:25 UTC, juzen2003 commented on opus/application/apps/help/api_guide.md
> +
Same here, might want to update the URL later.

2020-01-25 02:25 UTC, juzen2003 commented on opus/application/apps/help/api_guide.md
> +
I tried to run this link but didn't get any returned images: https://tools.pds-rings.seti.org/opus/api/images/med.html?volumeid=COISS_2002&startobs=10&limit=2, and if I ran through the test database, there will be 2 images: http://localhost:8000/opus/api/images/med.html?volumeid=COISS_2002&startobs=10&limit=2

2020-01-25 02:25 UTC, juzen2003 commented on opus/application/apps/help/api_guide.md
> +    "description": "Calibrated im
Return value with SURFACEGEO needs to be updated after merging with #965.

2020-01-25 02:25 UTC, juzen2003 commented on opus/application/apps/help/api_guide.md
> +    "description": "Calibrated im
Return value with SURFACEGEO needs to be updated after merging with #965.

2020-01-25 02:25 UTC, juzen2003 commented on opus/application/apps/help/api_guide.md
> +    "description": "Calibrated im
Return value with SURFACEGEO needs to be updated after merging with #965.

2020-01-25 02:25 UTC, juzen2003 commented on opus/application/apps/help/api_guide.md
> +    "description": "Calibrated im
SURFACEGEO slug needs to be updated after merging with #965.

2020-01-25 02:25 UTC, juzen2003 commented on opus/application/apps/help/templates/help/apiguide.html
> +                    </tr>
Indentations are a bit off for the tr tag

2020-01-25 02:25 UTC, juzen2003 commented on opus/application/apps/help/templates/help/apiguide.html
> +    		<tbody>
I think we don't need the indentation here.

2020-01-25 02:25 UTC, juzen2003 commented on opus/application/apps/help/templates/help/apiguide_print.html
> +		<tbody>
I think we don't need the indentation here.

2020-01-25 02:25 UTC, juzen2003 commented on opus/application/apps/help/templates/help/apiguide_print.html
> +		</tbody>
Indentations are off for tbody and tr tags.

2020-01-25 02:25 UTC, juzen2003 commented on opus/application/apps/results/templates/results/image_list.html
> +        </li>
li and /li not aligned.

2020-01-25 02:25 UTC, juzen2003 commented on opus/application/static_media/css/opus.css
> +   width: auto !important;
Missing one space.

2020-01-25 02:25 UTC, juzen2003 commented on opus/application/static_media/js/opus.js
> +        let pdf_url = false;
Maybe we want to use camel case when declaring variables in js code?

2020-01-25 02:25 UTC, juzen2003 commented on opus/application/static_media/js/opus.js
> +                    let pdf_url = $(".op-open-help-pdf").data("action");
Maybe we want to use camel case here?

2020-01-27 19:02 UTC, rfrenchseti commented on opus/application/apps/help/templates/help/about.html
> +			<a href="https://tools.pds-rings.seti.org/opus/#/SURFACEGEOplutocenterresolution2=5.00000&SURFACEGEOplutophase1=160.000&surfacegeometrytargetname=Pluto&qtype-SURFACEGEOplutophase=any&cols=opusid,i
Fixed

2020-01-27 19:04 UTC, rfrenchseti commented on opus/application/apps/help/api_guide.md
> +
Fixed

2020-01-27 19:04 UTC, rfrenchseti commented on opus/application/apps/help/api_guide.md
> +
Fixed

2020-01-27 19:04 UTC, rfrenchseti commented on opus/application/apps/help/api_guide.md
> +
Fixed

2020-01-27 19:05 UTC, rfrenchseti commented on opus/application/apps/help/api_guide.md
> +
Yes there was a bug in the current implementation and I fixed it.

2020-01-27 19:05 UTC, rfrenchseti commented on opus/application/apps/help/api_guide.md
> +    "description": "Calibrated im
Fixed

2020-01-27 19:05 UTC, rfrenchseti commented on opus/application/apps/help/api_guide.md
> +    "description": "Calibrated im
Fixed

2020-01-27 19:05 UTC, rfrenchseti commented on opus/application/apps/help/api_guide.md
> +    "description": "Calibrated im
Fixed

2020-01-27 19:05 UTC, rfrenchseti commented on opus/application/apps/help/api_guide.md
> +    "description": "Calibrated im
Fixed

2020-01-27 19:06 UTC, rfrenchseti commented on opus/application/apps/help/templates/help/apiguide.html
> +                    </tr>
Fixed

2020-01-27 19:06 UTC, rfrenchseti commented on opus/application/apps/help/templates/help/apiguide.html
> +    		<tbody>
Fixed

2020-01-27 19:07 UTC, rfrenchseti commented on opus/application/apps/help/templates/help/apiguide_print.html
> +		<tbody>
Fixed

2020-01-27 19:07 UTC, rfrenchseti commented on opus/application/apps/help/templates/help/apiguide_print.html
> +		</tbody>
Fixed

2020-01-27 19:08 UTC, rfrenchseti commented on opus/application/apps/results/templates/results/image_list.html
> +        </li>
Fixed

2020-01-27 19:08 UTC, rfrenchseti commented on opus/application/static_media/css/opus.css
> +   width: auto !important;
Fixed

2020-01-27 19:10 UTC, rfrenchseti commented on opus/application/static_media/js/opus.js
> +        let pdf_url = false;
Fixed

2020-01-27 19:10 UTC, rfrenchseti commented on opus/application/static_media/js/opus.js
> +                    let pdf_url = $(".op-open-help-pdf").data("action");
Fixed

2020-01-27 19:11 UTC, rfrenchseti reviewed
Changes made as requested

2020-01-27 21:09 UTC, juzen2003 approved these changes

2020-01-28 01:01 UTC, merged