Add regex string searches (Fixes #450)
SETI/rms-opus pull request #989
Opened 2020-02-08 02:28 UTC by rfrenchseti

- Fixes #450
- Were any Django, import pipeline, table_schema, or dictionary files modified? Y
  - Database used: opus3_test_200106
  - All Django tests pass: Y
- Were any JavaScript or CSS files modified? Y
  - JSHINT run on all affected files: Y
  - Tested on Chrome, Firefox, Safari, and iOS: Y
    (Remember to test all browser sizes)
  - Tested for race conditions (with delayed API calls if applicable): Y

Description of changes:

Implemented "regex" qtype for strings and added appropriate tests. Made UI do input validation on strings.

Known problems:

None.

2020-02-14 19:26 UTC, rfrenchseti commented
I've merged the current master into this branch and fixed the merge conflicts. All Django tests pass using `opus3_test_200211`. I also fixed one typo that caused a crash in the fake HTTP404 throws.

2020-02-14 19:32 UTC, rfrenchseti commented
Also, it turns out that the central planet is always in the target list even if it's not in the field of view. I've updated the tooltip and FAQ to talk about this.

2020-02-14 20:52 UTC, juzen2003 requested changes
- Issue: 
  - Add an API delay like 3s (OPUS_FAKE_API_DELAYS = 3000)
  - Open up surface geo target selector and multiple target list.
  - In multiple target, select regex in q-type.
  - In surface geo target selector, select "Saturn" and before the search completes:
    - Quickly focus in the input in multiple target, and type "^s.*$" or even just "s" and stay focus in the input with green border.
  - The results and widgets spinner will not go away until we focus out the input (or trigger a change event).
  - UPDATE: the issue can be reproduced with similar steps applying to a combination of mults and input widget, for example:
    - Add an API delay.
    - Open up volume id widget and select regex in qtype.
    - In planet widget, select "Pluto" and before the search completes:
      - Quickly focus in the input of volume id and type something like "\d".
    - The results and widgets spinner will not go away until a change is triggered and done.

- Note: the long multiple target list in autocomplete dropdown will go out of screen.

2020-02-14 20:52 UTC, juzen2003 commented on opus/application/apps/search/forms.py
>                      required = False,
Do we want to apply the 4 spaces indentation to attrs (https://www.python.org/dev/peps/pep-0008/#indentation)? Because it's an argument passed into widget.

2020-02-14 20:52 UTC, juzen2003 commented on opus/application/apps/search/test_search.py
> +        "[test_search.py] string_query: string query with qtype contains"
with qtype **regex**

2020-02-14 20:52 UTC, juzen2003 commented on opus/application/static_media/js/hash.js
> +                        // opus.InputFieldsValidation), we push it to the hash.
Use lower case i (```opus.inputFieldsValidation ```) to stick to JS variable naming convention.

2020-02-14 20:52 UTC, juzen2003 commented on opus/application/static_media/js/opus.js
> +    InputFieldsValidation: {},
Use lower case i when declaring ```inputFieldsValidation```.

2020-02-14 23:24 UTC, rfrenchseti commented on opus/application/apps/search/forms.py
>                      required = False,
Fixed. This whole file is a mess, though, and needs to be cleaned up.

2020-02-14 23:24 UTC, rfrenchseti commented on opus/application/apps/search/test_search.py
> +        "[test_search.py] string_query: string query with qtype contains"
Fixed

2020-02-14 23:26 UTC, rfrenchseti commented on opus/application/static_media/js/opus.js
> +    InputFieldsValidation: {},
Fixed everywhere in JS.

2020-02-14 23:26 UTC, rfrenchseti commented on opus/application/static_media/js/hash.js
> +                        // opus.InputFieldsValidation), we push it to the hash.
Fixed everywhere in JS.

2020-02-15 05:24 UTC, juzen2003 commented
- Database used: opus3_test_200211
- All Django tests pass: Y
- JSHINT run on all affected files: Y
- Tested on Chrome, Firefox, Safari, and iOS: Y
  (Remember to test all browser sizes)
- Tested for race conditions (with delayed API calls if applicable): Y

2020-02-15 05:25 UTC, juzen2003 approved these changes

2020-02-16 00:30 UTC, merged